#!/bin/bash
# ~/.config/borders/bordersrc
# Main JankyBorders configuration file

options=(
    active_color=0xfffcd049
    inactive_color=0x00d5dce3
    width=3.0
    hidpi=on
    ax_focus=on
    order=above
    style=uniform
)

borders "${options[@]}"
